// GENERATED by `npm run update-snapshot` — do not edit by hand.
//
// The models.dev price table, trimmed to the providers and fields this plugin
// reads, shipped so that a fresh install prices models without waiting on the
// network. A floor only: the on-disk cache and a live fetch both win over it.
//
// Fetched 2026-08-10 from https://models.dev/api.json — 129 models.

export const MODELS_DEV_SNAPSHOT: Record<string, unknown> = {
  "azure": {
    "id": "azure",
    "models": {
      "claude-fable-5": {
        "attachment": true,
        "cost": {
          "cache_read": 1,
          "cache_write": 12.5,
          "input": 10,
          "output": 50
        },
        "id": "claude-fable-5",
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-haiku-4-5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.1,
          "cache_write": 1.25,
          "input": 1,
          "output": 5
        },
        "id": "claude-haiku-4-5",
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-opus-4-1": {
        "attachment": true,
        "cost": {
          "cache_read": 1.5,
          "cache_write": 18.75,
          "input": 15,
          "output": 75
        },
        "id": "claude-opus-4-1",
        "limit": {
          "context": 200000,
          "output": 32000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-opus-4-5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "cache_write": 6.25,
          "input": 5,
          "output": 25
        },
        "id": "claude-opus-4-5",
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-opus-4-6": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "cache_write": 6.25,
          "context_over_200k": {
            "cache_read": 1,
            "cache_write": 12.5,
            "input": 10,
            "output": 37.5
          },
          "input": 5,
          "output": 25,
          "tiers": [
            {
              "cache_read": 1,
              "cache_write": 12.5,
              "input": 10,
              "output": 37.5,
              "tier": {
                "size": 200000,
                "type": "context"
              }
            }
          ]
        },
        "id": "claude-opus-4-6",
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-opus-4-8": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "cache_write": 6.25,
          "context_over_200k": {
            "cache_read": 1,
            "cache_write": 12.5,
            "input": 10,
            "output": 37.5
          },
          "input": 5,
          "output": 25,
          "tiers": [
            {
              "cache_read": 1,
              "cache_write": 12.5,
              "input": 10,
              "output": 37.5,
              "tier": {
                "size": 200000,
                "type": "context"
              }
            }
          ]
        },
        "id": "claude-opus-4-8",
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-opus-5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "cache_write": 6.25,
          "input": 5,
          "output": 25
        },
        "id": "claude-opus-5",
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-sonnet-4-5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.3,
          "cache_write": 3.75,
          "input": 3,
          "output": 15
        },
        "id": "claude-sonnet-4-5",
        "limit": {
          "context": 200000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-sonnet-4-6": {
        "attachment": true,
        "cost": {
          "cache_read": 0.3,
          "cache_write": 3.75,
          "input": 3,
          "output": 15
        },
        "id": "claude-sonnet-4-6",
        "limit": {
          "context": 1000000,
          "output": 64000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "claude-sonnet-5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.2,
          "cache_write": 2.5,
          "input": 2,
          "output": 10
        },
        "id": "claude-sonnet-5",
        "limit": {
          "context": 1000000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "codestral-2501": {
        "attachment": false,
        "cost": {
          "input": 0.3,
          "output": 0.9
        },
        "id": "codestral-2501",
        "limit": {
          "context": 256000,
          "output": 256000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "codex-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.375,
          "input": 1.5,
          "output": 6
        },
        "id": "codex-mini",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "cohere-command-a": {
        "attachment": false,
        "cost": {
          "input": 2.5,
          "output": 10
        },
        "id": "cohere-command-a",
        "limit": {
          "context": 131072,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "cohere-embed-v-4-0": {
        "attachment": true,
        "cost": {
          "input": 0.12,
          "output": 0
        },
        "id": "cohere-embed-v-4-0",
        "limit": {
          "context": 128000,
          "output": 1536
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "cohere-embed-v3-english": {
        "attachment": false,
        "cost": {
          "input": 0.1,
          "output": 0
        },
        "id": "cohere-embed-v3-english",
        "limit": {
          "context": 512,
          "output": 1024
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "cohere-embed-v3-multilingual": {
        "attachment": false,
        "cost": {
          "input": 0.1,
          "output": 0
        },
        "id": "cohere-embed-v3-multilingual",
        "limit": {
          "context": 512,
          "output": 1024
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "deepseek-r1": {
        "attachment": false,
        "cost": {
          "input": 1.35,
          "output": 5.4
        },
        "id": "deepseek-r1",
        "limit": {
          "context": 163840,
          "output": 163840
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": false
      },
      "deepseek-v3.2": {
        "attachment": false,
        "cost": {
          "input": 0.58,
          "output": 1.68
        },
        "id": "deepseek-v3.2",
        "limit": {
          "context": 128000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "deepseek-v3.2-speciale": {
        "attachment": false,
        "cost": {
          "input": 0.58,
          "output": 1.68
        },
        "id": "deepseek-v3.2-speciale",
        "limit": {
          "context": 128000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": false
      },
      "deepseek-v4-flash": {
        "attachment": false,
        "cost": {
          "input": 0.19,
          "output": 0.51
        },
        "id": "deepseek-v4-flash",
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": false
      },
      "deepseek-v4-pro": {
        "attachment": false,
        "cost": {
          "input": 1.74,
          "output": 3.48
        },
        "id": "deepseek-v4-pro",
        "limit": {
          "context": 1000000,
          "output": 384000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": false
      },
      "gpt-3.5-turbo-0125": {
        "attachment": false,
        "cost": {
          "input": 0.5,
          "output": 1.5
        },
        "id": "gpt-3.5-turbo-0125",
        "limit": {
          "context": 16384,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-3.5-turbo-1106": {
        "attachment": false,
        "cost": {
          "input": 1,
          "output": 2
        },
        "id": "gpt-3.5-turbo-1106",
        "limit": {
          "context": 16384,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-3.5-turbo-instruct": {
        "attachment": false,
        "cost": {
          "input": 1.5,
          "output": 2
        },
        "id": "gpt-3.5-turbo-instruct",
        "limit": {
          "context": 4096,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-4-turbo": {
        "attachment": true,
        "cost": {
          "input": 10,
          "output": 30
        },
        "id": "gpt-4-turbo",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4-turbo-vision": {
        "attachment": true,
        "cost": {
          "input": 10,
          "output": 30
        },
        "id": "gpt-4-turbo-vision",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4.1": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "input": 2,
          "output": 8
        },
        "id": "gpt-4.1",
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4.1-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.1,
          "input": 0.4,
          "output": 1.6
        },
        "id": "gpt-4.1-mini",
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4.1-nano": {
        "attachment": true,
        "cost": {
          "cache_read": 0.025,
          "input": 0.1,
          "output": 0.4
        },
        "id": "gpt-4.1-nano",
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4o": {
        "attachment": true,
        "cost": {
          "cache_read": 1.25,
          "input": 2.5,
          "output": 10
        },
        "id": "gpt-4o",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4o-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.075,
          "input": 0.15,
          "output": 0.6
        },
        "id": "gpt-4o-mini",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.13,
          "input": 1.25,
          "output": 10
        },
        "id": "gpt-5",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5-codex": {
        "attachment": false,
        "cost": {
          "cache_read": 0.13,
          "input": 1.25,
          "output": 10
        },
        "id": "gpt-5-codex",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.03,
          "input": 0.25,
          "output": 2
        },
        "id": "gpt-5-mini",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5-nano": {
        "attachment": true,
        "cost": {
          "cache_read": 0.01,
          "input": 0.05,
          "output": 0.4
        },
        "id": "gpt-5-nano",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5-pro": {
        "attachment": true,
        "cost": {
          "input": 15,
          "output": 120
        },
        "id": "gpt-5-pro",
        "limit": {
          "context": 400000,
          "output": 272000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.1": {
        "attachment": true,
        "cost": {
          "cache_read": 0.125,
          "input": 1.25,
          "output": 10
        },
        "id": "gpt-5.1",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "audio"
          ],
          "output": [
            "text",
            "image",
            "audio"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.1-codex": {
        "attachment": false,
        "cost": {
          "cache_read": 0.125,
          "input": 1.25,
          "output": 10
        },
        "id": "gpt-5.1-codex",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "audio"
          ],
          "output": [
            "text",
            "image",
            "audio"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.1-codex-max": {
        "attachment": true,
        "cost": {
          "cache_read": 0.125,
          "input": 1.25,
          "output": 10
        },
        "id": "gpt-5.1-codex-max",
        "limit": {
          "context": 400000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.1-codex-mini": {
        "attachment": false,
        "cost": {
          "cache_read": 0.025,
          "input": 0.25,
          "output": 2
        },
        "id": "gpt-5.1-codex-mini",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.2": {
        "attachment": true,
        "cost": {
          "cache_read": 0.125,
          "input": 1.75,
          "output": 14
        },
        "id": "gpt-5.2",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.2-codex": {
        "attachment": false,
        "cost": {
          "cache_read": 0.175,
          "input": 1.75,
          "output": 14
        },
        "id": "gpt-5.2-codex",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.3-codex": {
        "attachment": false,
        "cost": {
          "cache_read": 0.175,
          "input": 1.75,
          "output": 14
        },
        "id": "gpt-5.3-codex",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.4": {
        "attachment": true,
        "cost": {
          "cache_read": 0.25,
          "context_over_200k": {
            "cache_read": 0.5,
            "input": 5,
            "output": 22.5
          },
          "input": 2.5,
          "output": 15,
          "tiers": [
            {
              "cache_read": 0.5,
              "input": 5,
              "output": 22.5,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.4",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.4-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.075,
          "input": 0.75,
          "output": 4.5
        },
        "id": "gpt-5.4-mini",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.4-nano": {
        "attachment": true,
        "cost": {
          "cache_read": 0.02,
          "input": 0.2,
          "output": 1.25
        },
        "id": "gpt-5.4-nano",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.4-pro": {
        "attachment": true,
        "cost": {
          "context_over_200k": {
            "input": 60,
            "output": 270
          },
          "input": 30,
          "output": 180,
          "tiers": [
            {
              "input": 60,
              "output": 270,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.4-pro",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "context_over_200k": {
            "cache_read": 1,
            "input": 10,
            "output": 45
          },
          "input": 5,
          "output": 30,
          "tiers": [
            {
              "cache_read": 1,
              "input": 10,
              "output": 45,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.5",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.6-luna": {
        "attachment": true,
        "cost": {
          "cache_read": 0.1,
          "cache_write": 1.25,
          "context_over_200k": {
            "cache_read": 0.2,
            "cache_write": 2.5,
            "input": 2,
            "output": 9
          },
          "input": 1,
          "output": 6,
          "tiers": [
            {
              "cache_read": 0.2,
              "cache_write": 2.5,
              "input": 2,
              "output": 9,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.6-luna",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.6-sol": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "context_over_200k": {
            "cache_read": 1,
            "input": 10,
            "output": 45
          },
          "input": 5,
          "output": 30,
          "tiers": [
            {
              "cache_read": 1,
              "input": 10,
              "output": 45,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.6-sol",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.6-terra": {
        "attachment": true,
        "cost": {
          "cache_read": 0.25,
          "cache_write": 3.125,
          "context_over_200k": {
            "cache_read": 0.5,
            "cache_write": 6.25,
            "input": 5,
            "output": 22.5
          },
          "input": 2.5,
          "output": 15,
          "tiers": [
            {
              "cache_read": 0.5,
              "cache_write": 6.25,
              "input": 5,
              "output": 22.5,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.6-terra",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-chat-latest": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "input": 5,
          "output": 30
        },
        "id": "gpt-chat-latest",
        "limit": {
          "context": 128000,
          "input": 111616,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-image-1": {
        "attachment": true,
        "cost": {
          "cache_read": 1.25,
          "input": 5,
          "output": 40
        },
        "id": "gpt-image-1",
        "limit": {
          "context": 0,
          "output": 0
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "image"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-image-1.5": {
        "attachment": true,
        "cost": {
          "cache_read": 1.25,
          "input": 5,
          "output": 32
        },
        "id": "gpt-image-1.5",
        "limit": {
          "context": 0,
          "output": 0
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text",
            "image"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-image-2": {
        "attachment": true,
        "cost": {
          "cache_read": 1.25,
          "input": 5,
          "output": 30
        },
        "id": "gpt-image-2",
        "limit": {
          "context": 0,
          "output": 0
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "image"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "grok-4-1-fast-non-reasoning": {
        "attachment": true,
        "cost": {
          "cache_read": 0.05,
          "input": 0.2,
          "output": 0.5
        },
        "id": "grok-4-1-fast-non-reasoning",
        "limit": {
          "context": 128000,
          "input": 128000,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "grok-4-1-fast-reasoning": {
        "attachment": true,
        "cost": {
          "cache_read": 0.05,
          "input": 0.2,
          "output": 0.5
        },
        "id": "grok-4-1-fast-reasoning",
        "limit": {
          "context": 128000,
          "input": 128000,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "grok-4-20-non-reasoning": {
        "attachment": false,
        "cost": {
          "input": 2,
          "output": 6
        },
        "id": "grok-4-20-non-reasoning",
        "limit": {
          "context": 262000,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "grok-4-20-reasoning": {
        "attachment": false,
        "cost": {
          "input": 2,
          "output": 6
        },
        "id": "grok-4-20-reasoning",
        "limit": {
          "context": 262000,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "kimi-k2.5": {
        "attachment": false,
        "cost": {
          "input": 0.6,
          "output": 3
        },
        "id": "kimi-k2.5",
        "limit": {
          "context": 262144,
          "output": 262144
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "kimi-k2.6": {
        "attachment": false,
        "cost": {
          "input": 0.95,
          "output": 4
        },
        "id": "kimi-k2.6",
        "limit": {
          "context": 262144,
          "output": 262144
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "kimi-k2.7-code": {
        "attachment": true,
        "cost": {
          "cache_read": 0.19,
          "input": 0.95,
          "output": 4
        },
        "id": "kimi-k2.7-code",
        "limit": {
          "context": 262144,
          "output": 262144
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "llama-3.3-70b-instruct": {
        "attachment": false,
        "cost": {
          "input": 0.71,
          "output": 0.71
        },
        "id": "llama-3.3-70b-instruct",
        "limit": {
          "context": 128000,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "llama-4-maverick-17b-128e-instruct-fp8": {
        "attachment": true,
        "cost": {
          "input": 0.25,
          "output": 1
        },
        "id": "llama-4-maverick-17b-128e-instruct-fp8",
        "limit": {
          "context": 1000000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "llama-4-scout-17b-16e-instruct": {
        "attachment": true,
        "cost": {
          "input": 0.2,
          "output": 0.78
        },
        "id": "llama-4-scout-17b-16e-instruct",
        "limit": {
          "context": 128000,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "ministral-3b": {
        "attachment": false,
        "cost": {
          "input": 0.04,
          "output": 0.04
        },
        "id": "ministral-3b",
        "limit": {
          "context": 128000,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "mistral-medium-2505": {
        "attachment": true,
        "cost": {
          "input": 0.4,
          "output": 2
        },
        "id": "mistral-medium-2505",
        "limit": {
          "context": 128000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "mistral-small-2503": {
        "attachment": true,
        "cost": {
          "input": 0.1,
          "output": 0.3
        },
        "id": "mistral-small-2503",
        "limit": {
          "context": 128000,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "model-router": {
        "attachment": true,
        "cost": {
          "input": 0.14,
          "output": 0
        },
        "id": "model-router",
        "limit": {
          "context": 200000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "o1": {
        "attachment": false,
        "cost": {
          "cache_read": 7.5,
          "input": 15,
          "output": 60
        },
        "id": "o1",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o3": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "input": 2,
          "output": 8
        },
        "id": "o3",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o3-mini": {
        "attachment": false,
        "cost": {
          "cache_read": 0.55,
          "input": 1.1,
          "output": 4.4
        },
        "id": "o3-mini",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o4-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.275,
          "input": 1.1,
          "output": 4.4
        },
        "id": "o4-mini",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "phi-4": {
        "attachment": false,
        "cost": {
          "input": 0.125,
          "output": 0.5
        },
        "id": "phi-4",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "phi-4-mini": {
        "attachment": false,
        "cost": {
          "input": 0.075,
          "output": 0.3
        },
        "id": "phi-4-mini",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "phi-4-mini-reasoning": {
        "attachment": false,
        "cost": {
          "input": 0.075,
          "output": 0.3
        },
        "id": "phi-4-mini-reasoning",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "phi-4-multimodal": {
        "attachment": true,
        "cost": {
          "input": 0.08,
          "input_audio": 4,
          "output": 0.32
        },
        "id": "phi-4-multimodal",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "audio"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "phi-4-reasoning": {
        "attachment": false,
        "cost": {
          "input": 0.125,
          "output": 0.5
        },
        "id": "phi-4-reasoning",
        "limit": {
          "context": 32000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": false
      },
      "phi-4-reasoning-plus": {
        "attachment": false,
        "cost": {
          "input": 0.125,
          "output": 0.5
        },
        "id": "phi-4-reasoning-plus",
        "limit": {
          "context": 32000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": false
      },
      "text-embedding-3-large": {
        "attachment": false,
        "cost": {
          "input": 0.13,
          "output": 0
        },
        "id": "text-embedding-3-large",
        "limit": {
          "context": 8191,
          "output": 3072
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "text-embedding-3-small": {
        "attachment": false,
        "cost": {
          "input": 0.02,
          "output": 0
        },
        "id": "text-embedding-3-small",
        "limit": {
          "context": 8191,
          "output": 1536
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "text-embedding-ada-002": {
        "attachment": false,
        "cost": {
          "input": 0.1,
          "output": 0
        },
        "id": "text-embedding-ada-002",
        "limit": {
          "context": 8192,
          "output": 1536
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      }
    }
  },
  "openai": {
    "id": "openai",
    "models": {
      "chatgpt-image-latest": {
        "attachment": true,
        "id": "chatgpt-image-latest",
        "limit": {
          "context": 0,
          "input": 0,
          "output": 0
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text",
            "image"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-3.5-turbo": {
        "attachment": false,
        "cost": {
          "cache_read": 0,
          "input": 0.5,
          "output": 1.5
        },
        "id": "gpt-3.5-turbo",
        "limit": {
          "context": 16385,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-4": {
        "attachment": true,
        "cost": {
          "input": 30,
          "output": 60
        },
        "id": "gpt-4",
        "limit": {
          "context": 8192,
          "output": 8192
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4-turbo": {
        "attachment": true,
        "cost": {
          "input": 10,
          "output": 30
        },
        "id": "gpt-4-turbo",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4.1": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "input": 2,
          "output": 8
        },
        "id": "gpt-4.1",
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4.1-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.1,
          "input": 0.4,
          "output": 1.6
        },
        "id": "gpt-4.1-mini",
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4.1-nano": {
        "attachment": true,
        "cost": {
          "cache_read": 0.025,
          "input": 0.1,
          "output": 0.4
        },
        "id": "gpt-4.1-nano",
        "limit": {
          "context": 1047576,
          "output": 32768
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4o": {
        "attachment": true,
        "cost": {
          "cache_read": 1.25,
          "input": 2.5,
          "output": 10
        },
        "id": "gpt-4o",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4o-2024-05-13": {
        "attachment": true,
        "cost": {
          "input": 5,
          "output": 15
        },
        "id": "gpt-4o-2024-05-13",
        "limit": {
          "context": 128000,
          "output": 4096
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4o-2024-08-06": {
        "attachment": true,
        "cost": {
          "cache_read": 1.25,
          "input": 2.5,
          "output": 10
        },
        "id": "gpt-4o-2024-08-06",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4o-2024-11-20": {
        "attachment": true,
        "cost": {
          "cache_read": 1.25,
          "input": 2.5,
          "output": 10
        },
        "id": "gpt-4o-2024-11-20",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-4o-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.075,
          "input": 0.15,
          "output": 0.6
        },
        "id": "gpt-4o-mini",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.125,
          "input": 1.25,
          "output": 10
        },
        "id": "gpt-5",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.025,
          "input": 0.25,
          "output": 2
        },
        "id": "gpt-5-mini",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5-nano": {
        "attachment": true,
        "cost": {
          "cache_read": 0.005,
          "input": 0.05,
          "output": 0.4
        },
        "id": "gpt-5-nano",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5-pro": {
        "attachment": true,
        "cost": {
          "input": 15,
          "output": 120
        },
        "id": "gpt-5-pro",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 272000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.1": {
        "attachment": true,
        "cost": {
          "cache_read": 0.125,
          "input": 1.25,
          "output": 10
        },
        "id": "gpt-5.1",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.2": {
        "attachment": true,
        "cost": {
          "cache_read": 0.175,
          "input": 1.75,
          "output": 14
        },
        "id": "gpt-5.2",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.2-chat-latest": {
        "attachment": true,
        "cost": {
          "cache_read": 0.175,
          "input": 1.75,
          "output": 14
        },
        "id": "gpt-5.2-chat-latest",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.2-pro": {
        "attachment": true,
        "cost": {
          "input": 21,
          "output": 168
        },
        "id": "gpt-5.2-pro",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.3-chat-latest": {
        "attachment": true,
        "cost": {
          "cache_read": 0.175,
          "input": 1.75,
          "output": 14
        },
        "id": "gpt-5.3-chat-latest",
        "limit": {
          "context": 128000,
          "output": 16384
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": true
      },
      "gpt-5.3-codex": {
        "attachment": true,
        "cost": {
          "cache_read": 0.175,
          "input": 1.75,
          "output": 14
        },
        "id": "gpt-5.3-codex",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.3-codex-spark": {
        "attachment": true,
        "cost": {
          "cache_read": 0.175,
          "input": 1.75,
          "output": 14
        },
        "id": "gpt-5.3-codex-spark",
        "limit": {
          "context": 128000,
          "input": 100000,
          "output": 32000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.4": {
        "attachment": true,
        "cost": {
          "cache_read": 0.25,
          "context_over_200k": {
            "cache_read": 0.5,
            "input": 5,
            "output": 22.5
          },
          "input": 2.5,
          "output": 15,
          "tiers": [
            {
              "cache_read": 0.5,
              "input": 5,
              "output": 22.5,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.4",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.4-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.075,
          "input": 0.75,
          "output": 4.5
        },
        "id": "gpt-5.4-mini",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.4-nano": {
        "attachment": true,
        "cost": {
          "cache_read": 0.02,
          "input": 0.2,
          "output": 1.25
        },
        "id": "gpt-5.4-nano",
        "limit": {
          "context": 400000,
          "input": 272000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.4-pro": {
        "attachment": true,
        "cost": {
          "context_over_200k": {
            "input": 60,
            "output": 270
          },
          "input": 30,
          "output": 180,
          "tiers": [
            {
              "input": 60,
              "output": 270,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.4-pro",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.5": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "context_over_200k": {
            "cache_read": 1,
            "input": 10,
            "output": 45
          },
          "input": 5,
          "output": 30,
          "tiers": [
            {
              "cache_read": 1,
              "input": 10,
              "output": 45,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.5",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.5-pro": {
        "attachment": true,
        "cost": {
          "context_over_200k": {
            "input": 60,
            "output": 270
          },
          "input": 30,
          "output": 180,
          "tiers": [
            {
              "input": 60,
              "output": 270,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.5-pro",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.6": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "cache_write": 6.25,
          "context_over_200k": {
            "cache_read": 1,
            "cache_write": 12.5,
            "input": 10,
            "output": 45
          },
          "input": 5,
          "output": 30,
          "tiers": [
            {
              "cache_read": 1,
              "cache_write": 12.5,
              "input": 10,
              "output": 45,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.6",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.6-luna": {
        "attachment": true,
        "cost": {
          "cache_read": 0.02,
          "cache_write": 0.25,
          "context_over_200k": {
            "cache_read": 0.04,
            "cache_write": 0.5,
            "input": 0.4,
            "output": 1.8
          },
          "input": 0.2,
          "output": 1.2,
          "tiers": [
            {
              "cache_read": 0.04,
              "cache_write": 0.5,
              "input": 0.4,
              "output": 1.8,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.6-luna",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.6-sol": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "cache_write": 6.25,
          "context_over_200k": {
            "cache_read": 1,
            "cache_write": 12.5,
            "input": 10,
            "output": 45
          },
          "input": 5,
          "output": 30,
          "tiers": [
            {
              "cache_read": 1,
              "cache_write": 12.5,
              "input": 10,
              "output": 45,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.6-sol",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-5.6-terra": {
        "attachment": true,
        "cost": {
          "cache_read": 0.2,
          "cache_write": 2.5,
          "context_over_200k": {
            "cache_read": 0.4,
            "cache_write": 5,
            "input": 4,
            "output": 18
          },
          "input": 2,
          "output": 12,
          "tiers": [
            {
              "cache_read": 0.4,
              "cache_write": 5,
              "input": 4,
              "output": 18,
              "tier": {
                "size": 272000,
                "type": "context"
              }
            }
          ]
        },
        "id": "gpt-5.6-terra",
        "limit": {
          "context": 1050000,
          "input": 922000,
          "output": 128000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "gpt-image-1": {
        "attachment": true,
        "id": "gpt-image-1",
        "limit": {
          "context": 0,
          "input": 0,
          "output": 0
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "image"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-image-1-mini": {
        "attachment": true,
        "id": "gpt-image-1-mini",
        "limit": {
          "context": 0,
          "input": 0,
          "output": 0
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text",
            "image"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-image-1.5": {
        "attachment": true,
        "id": "gpt-image-1.5",
        "limit": {
          "context": 0,
          "input": 0,
          "output": 0
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text",
            "image"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-image-2": {
        "attachment": true,
        "cost": {
          "cache_read": 1.25,
          "input": 5,
          "output": 30
        },
        "id": "gpt-image-2",
        "limit": {
          "context": 0,
          "input": 0,
          "output": 0
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "image"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "gpt-realtime-2.1": {
        "attachment": true,
        "cost": {
          "cache_read": 0.4,
          "input": 4,
          "input_audio": 32,
          "output": 24,
          "output_audio": 64
        },
        "id": "gpt-realtime-2.1",
        "limit": {
          "context": 128000,
          "input": 96000,
          "output": 32000
        },
        "modalities": {
          "input": [
            "text",
            "audio",
            "image"
          ],
          "output": [
            "text",
            "audio"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o1": {
        "attachment": true,
        "cost": {
          "cache_read": 7.5,
          "input": 15,
          "output": 60
        },
        "id": "o1",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o1-pro": {
        "attachment": true,
        "cost": {
          "input": 150,
          "output": 600
        },
        "id": "o1-pro",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o3": {
        "attachment": true,
        "cost": {
          "cache_read": 0.5,
          "input": 2,
          "output": 8
        },
        "id": "o3",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image",
            "pdf"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o3-mini": {
        "attachment": false,
        "cost": {
          "cache_read": 0.55,
          "input": 1.1,
          "output": 4.4
        },
        "id": "o3-mini",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o3-pro": {
        "attachment": true,
        "cost": {
          "input": 20,
          "output": 80
        },
        "id": "o3-pro",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "o4-mini": {
        "attachment": true,
        "cost": {
          "cache_read": 0.275,
          "input": 1.1,
          "output": 4.4
        },
        "id": "o4-mini",
        "limit": {
          "context": 200000,
          "output": 100000
        },
        "modalities": {
          "input": [
            "text",
            "image"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": true,
        "tool_call": true
      },
      "text-embedding-3-large": {
        "attachment": false,
        "cost": {
          "input": 0.13,
          "output": 0
        },
        "id": "text-embedding-3-large",
        "limit": {
          "context": 8191,
          "output": 3072
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "text-embedding-3-small": {
        "attachment": false,
        "cost": {
          "input": 0.02,
          "output": 0
        },
        "id": "text-embedding-3-small",
        "limit": {
          "context": 8191,
          "output": 1536
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      },
      "text-embedding-ada-002": {
        "attachment": false,
        "cost": {
          "input": 0.1,
          "output": 0
        },
        "id": "text-embedding-ada-002",
        "limit": {
          "context": 8192,
          "output": 1536
        },
        "modalities": {
          "input": [
            "text"
          ],
          "output": [
            "text"
          ]
        },
        "reasoning": false,
        "tool_call": false
      }
    }
  }
}
